pretzel:
  engine: liquid
exclude:
- publish.ps1
- build.cake
- build.ps1
- tools\
- .vscode\
- .git\
- .git
- .gitignore
- add-post.cmd
- add-tag.cmd
- add-draft.cmd
- taste.cmd
- taste-drafts.cmd
- git-clean.cmd
- build.bat
- cake.config
include:
- downloads
author: Manuel Grundner
author-email: m.grundner@delegate.at
disqus-shortname: delegateat
main-url: http://www.delegate.at
site-name: blog.delegate.at
feed-name: blog.delegate.at
site-url: http://blog.delegate.at
version: 0.1.0+150
commit: 6782d1697b983153c4aaf4760d1f20e2537bd16e
last-update: 2018-05-12
