pretzel:
  engine: liquid
exclude:
- publish.ps1
- build.cake
- build.ps1
- tools\
- .vscode\
- .git\
- .git
- .gitignore
- add-post.cmd
- add-tag.cmd
- add-draft.cmd
- taste.cmd
- taste-drafts.cmd
- git-clean.cmd
- build.bat
- cake.config
- tests\
include:
- downloads
author: Manuel Grundner
author-email: m.grundner@delegate.at
disqus-shortname: delegateat
main-url: http://www.delegate.at
site-name: blog.delegate.at
feed-name: blog.delegate.at
site-url: http://blog.delegate.at
version: 0.1.0+164
commit: 6647645fef71cb7041a9f48db5ca7bf17cca79fd
last-update: 2018-10-13
