pretzel:
  engine: liquid
exclude:
- publish.ps1
- build.cake
- build.ps1
- tools\
- .vscode\
- .git\
- .git
- .gitignore
- add-tag.cmd
author: Manuel Grundner
author-email: m.grundner@delegate.at
disqus-shortname: delegateat
main-url: http://www.delegate.at
site-name: blog.delegate.at
feed-name: blog.delegate.at
site-url: http://blog.delegate.at
version: 0.1.0+131
commit: 72ed23e1faaf16d9066e1cf89f867c43f7f88899
last-update: 2018-04-14
